version: '3.8'

services:
  redis:
    image: redis:3.2
    container_name: redis
    ports:
      - 6379:6379
    command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes
    volumes:
      - ./data:/data
      - /tmp/redis:/tmp/redis
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf